// Generated by CoffeeScript 1.8.0
(function() {
  var define_controller;

  define('chat', function() {
    return {
      name: 'chat',
      title: 'Chat Room',
      icon: 'icon-chat',
      type: 'plugin',
      init: function() {
        foundry.initialized(this.name);
        return define_controller();
      },
      inited: function() {
        return console.log('end');
      }
    };
  });

  define_controller = function() {
    return angular.module('foundry').controller('ChatController', [
      '$scope', function($scope) {
        $scope.load = function() {
          return console.log('load all messages');
        };
        $scope.send = function() {
          return console.log('send this');
        };
        return $scope.load();
      }
    ]);
  };

}).call(this);
